"""
Integration tests — challenging and super-challenging queries through the full pipeline.
No mocks: real Ollama inference + real DB execution.

Assertions compare model results against ground truth values queried directly from the DB.
"""
import pytest

from tests.integration.conftest import find_col, numeric_col, str_col

TOLERANCE = 0.05  # 5% tolerance for revenue comparisons


def _within_tolerance(actual: float, expected: float, tol: float = TOLERANCE) -> bool:
    if expected == 0:
        return actual == 0
    return abs(actual - expected) / abs(expected) <= tol


# ─────────────────────────────────────────────────────────────────────────────
# Ground truth constants
# ─────────────────────────────────────────────────────────────────────────────
GROUND_TRUTH_EARLIEST_DATE_REVENUE = 4_467_600
GROUND_TRUTH_BEST_GROSS_MONTH = (2024, 10, 109_339_350)
GROUND_TRUTH_TOP_FRIDAY_WAITER = "Vendedor 103"
GROUND_TRUTH_TOP_AVG_ITEMS_WAITER = ("Vendedor 116", 3.01)
GROUND_TRUTH_TOP_COPURCHASED = (4, 9, 416)  # product_a, product_b, count
GROUND_TRUTH_TOTAL_REVENUE = 211_994_375


# ═════════════════════════════════════════════════════════════════════════════
# CHALLENGING TESTS
# ═════════════════════════════════════════════════════════════════════════════

@pytest.mark.integration
async def test_revenue_on_earliest_date(ask):
    """Revenue on the earliest date uses MIN(sale_date) subquery and proper JOIN."""
    body = await ask("How much did we sell on the earliest date in the database?")
    results = body["results"]
    assert len(results) >= 1
    total = numeric_col(results[0], "revenue", "total", "sum", "amount")
    assert _within_tolerance(total, GROUND_TRUTH_EARLIEST_DATE_REVENUE)


@pytest.mark.integration
async def test_month_with_highest_gross_revenue(ask):
    """Identifies the single best month by gross revenue, excluding returns."""
    body = await ask("Which month had the highest gross revenue from forward sales only?")
    results = body["results"]
    assert len(results) >= 1
    month_key = find_col(results[0], "month")
    if month_key is not None:
        month = int(float(results[0][month_key]))
        assert month == GROUND_TRUTH_BEST_GROSS_MONTH[1], (
            f"Expected month {GROUND_TRUTH_BEST_GROSS_MONTH[1]}, got {month}"
        )


@pytest.mark.integration
async def test_waiter_revenue_on_fridays(ask):
    """Revenue per waiter restricted to Friday sales only."""
    body = await ask("What is the total revenue generated by each waiter on Fridays?")
    results = body["results"]
    assert len(results) >= 1
    # Top Friday earner should be Vendedor 103
    top_name = str_col(results[0], "waiter", "name")
    assert GROUND_TRUTH_TOP_FRIDAY_WAITER in top_name


@pytest.mark.integration
async def test_forward_vs_return_revenue_per_product(ask):
    """Per-product breakdown of forward revenue vs return revenue via CASE WHEN."""
    body = await ask("Show me the forward sales revenue and return revenue for the top 10 products.")
    results = body["results"]
    assert len(results) >= 1
    for row in results:
        assert str_col(row, "product", "name")
        # If both forward and net columns exist, check net <= forward invariant
        fwd_key = find_col(row, "forward")
        net_key = find_col(row, "net")
        if fwd_key and net_key:
            forward = float(row[fwd_key])
            net = float(row[net_key])
            assert net <= forward + 0.01, f"net ({net}) > forward ({forward})"


@pytest.mark.integration
async def test_avg_items_per_ticket_per_waiter(ask):
    """Average number of items per forward-sale ticket, grouped by waiter."""
    body = await ask("What is the average number of items per ticket for each waiter on forward sales?")
    results = body["results"]
    assert len(results) >= 1
    # Top waiter by avg items/ticket should be Vendedor 116
    top_name = str_col(results[0], "waiter", "name")
    assert GROUND_TRUTH_TOP_AVG_ITEMS_WAITER[0] in top_name
    avg_key = find_col(results[0], "avg")
    if avg_key is not None:
        avg = float(results[0][avg_key])
        assert _within_tolerance(avg, GROUND_TRUTH_TOP_AVG_ITEMS_WAITER[1])


# ═════════════════════════════════════════════════════════════════════════════
# SUPER-CHALLENGING TESTS
# ═════════════════════════════════════════════════════════════════════════════

@pytest.mark.integration
async def test_product_revenue_rank_window_function(ask):
    """RANK() window function assigns ordinal rank to each product by revenue."""
    body = await ask("Rank all products by their total revenue using a window function.")
    results = body["results"]
    assert len(results) >= 1
    rank_key = find_col(results[0], "rank")
    if rank_key is not None:
        assert int(results[0][rank_key]) == 1, "First row must have rank 1"
        ranks = [int(r[rank_key]) for r in results]
        assert ranks == sorted(ranks), "Ranks must be non-decreasing"


@pytest.mark.integration
async def test_product_revenue_percentage_share(ask):
    """Each product's revenue as a % of total using SUM() OVER () window aggregate."""
    body = await ask("What percentage of total revenue does each product contribute?")
    results = body["results"]
    assert len(results) >= 1
    pct_key = find_col(results[0], "pct", "percent", "share")
    if pct_key is not None:
        pcts = [float(r[pct_key]) for r in results]
        for pct in pcts:
            assert 0 <= pct <= 100, f"Percentage {pct} out of 0-100 range"
        total_pct = sum(pcts)
        assert 99.0 <= total_pct <= 101.0, f"Percentages sum to {total_pct}, expected ~100"


@pytest.mark.integration
async def test_top_copurchased_product_pairs(ask):
    """Self-join on sale_items identifies the most frequently co-purchased pairs."""
    body = await ask("Which pairs of products are most frequently bought together in the same ticket?")
    results = body["results"]
    assert len(results) >= 1
    # Top pair count should be around 416
    top_count = numeric_col(results[0], "count", "co_purchase", "frequency", "pair")
    assert _within_tolerance(top_count, GROUND_TRUTH_TOP_COPURCHASED[2])


@pytest.mark.integration
async def test_cumulative_daily_revenue(ask):
    """Running total of daily revenue using ordered window aggregate."""
    body = await ask("Show daily revenue and its running cumulative total ordered by date.")
    results = body["results"]
    assert len(results) >= 2, "Expected data spanning at least 2 days"
    # Final cumulative should approximate total revenue
    cum_key = find_col(results[-1], "cumulative", "running", "cum")
    if cum_key is not None:
        last_cum = float(results[-1][cum_key])
        assert _within_tolerance(last_cum, GROUND_TRUTH_TOTAL_REVENUE)


@pytest.mark.integration
async def test_top_waiter_best_products_via_cte(ask):
    """Two-stage CTE: identify highest-revenue waiter, then their top 3 products."""
    body = await ask("What are the top 3 best-selling products sold by the highest-revenue waiter?")
    results = body["results"]
    assert 1 <= len(results) <= 10
    for row in results:
        assert str_col(row, "product", "name")
        qty = numeric_col(row, "quantity", "qty", "total", "count")
        assert qty > 0
